### ISSUE TITLE
AWS Lightsail scrypt.scrypt.error: could not compute hash

### ISSUE THREAD

**Issue by joshteng** [holgern/py-scrypt#13]
Not sure how to solve this. My code works on various machines but not my AWS Lightsail instance.

I tried running the test. The error:
```
======================================================================
ERROR: test_hash_vectors_from_csv (scrypt.tests.test_scrypt.TestScryptHash)
Test hash function with precalculated combinations
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/py-scrypt/scrypt/tests/test_scrypt.py", line 194, in test_hash_vectors_from_csv
    h = scrypt.hash(row[0], row[1], int(row[2]), int(row[3]), int(row[4]))
  File "/home/py-scrypt/scrypt/scrypt.py", line 236, in hash
    raise error('could not compute hash')
scrypt.scrypt.error: could not compute hash

----------------------------------------------------------------------
Ran 50 tests in 12.822s

FAILED (errors=1, skipped=5)
Test failed: <unittest.runner.TextTestResult run=50 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=50 errors=1 failures=0>
```

```sh
uname -a
Linux 1ed1ff8d0158 5.4.0-1018-aws #18-Ubuntu SMP Wed Jun 24 01:15:00 UTC 2020 x86_64 GNU/Linux
```

Lightsail Instance:
```
1 GB RAM, 1 vCPU, 40 GB SSD
Ubuntu
```

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
```

**Comment by joshteng** [comment]
Figured it out. Resource issue. 2GB instance works. 1GB instance doesn't. -.-
